apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibmmq-operator-group
spec:
  targetNamespaces:
  - ibmmq-camel-spring-boot-project
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
  namespace: openshift-operators 
spec:
  channel: v3.3
  name: ibm-mq 
  source: ibm-operator-catalog 
  sourceNamespace: openshift-marketplace